name = "test"
type = "javascript"  # 使用 JavaScript 类型，适用于 Worker 代码

[build]
command = "npm run build"  # 根据你的构建工具设置
directory = "dist"  # 如果使用构建工具，构建文件会输出到此目录

[env.production]
workers_dev = false

[build.upload]
format = "service-worker"  # 适用于 Workers 服务
